using Cronos;
using System;

namespace shop_back.src.Shared.Infrastructure.Helpers
{
    public static class CronHelper
    {
        /// <summary>
        /// Generates a cron expression from a simple interval value and unit.
        /// </summary>
        /// <param name="value">The interval number (must be >= 1).</param>
        /// <param name="unit">Unit: minutes, hours, days, weeks, months, years.</param>
        /// <returns>A cron expression string.</returns>
        public static string GenerateCronExpression(int value, string unit)
        {
            if (value < 1) value = 1;
            unit = unit?.ToLower() ?? "days";

            return unit switch
            {
                "minutes" => $"*/{value} * * * *",
                "hours"   => $"0 */{value} * * *",
                "days"    => $"0 0 */{value} * *",
                "weeks"   => $"0 0 */{value * 7} * *",
                "months"  => $"0 0 1 */{value} *",
                "years"   => $"0 0 1 1 */{value * 12}",
                _         => $"0 0 */{value} * *"
            };
        }

        /// <summary>
        /// Parses a cron expression back into a human-readable interval (for display).
        /// </summary>
        /// <param name="cronExpression">The cron string.</param>
        /// <returns>A tuple (value, unit) or null if not recognized.</returns>
        public static (int Value, string Unit)? ParseCronToInterval(string cronExpression)
        {
            if (string.IsNullOrWhiteSpace(cronExpression))
                return null;

            var parts = cronExpression.Split(' ');
            if (parts.Length < 5) 
                return null;

            // Simple pattern matching for the most common patterns generated by our helper
            if (parts[0] == "0" && parts[1] == "0" && parts[2] == "1" && parts[3] == "1" && parts[4].StartsWith("*/"))
            {
                if (int.TryParse(parts[4].Substring(2), out var val))
                    return (val / 12, "years");
            }
            else if (parts[0] == "0" && parts[1] == "0" && parts[2] == "1" && parts[3].StartsWith("*/"))
            {
                if (int.TryParse(parts[3].Substring(2), out var val))
                    return (val, "months");
            }
            else if (parts[0] == "0" && parts[1] == "0" && parts[2].StartsWith("*/"))
            {
                if (int.TryParse(parts[2].Substring(2), out var val))
                {
                    // Check if it's a multiple of 7 (weeks)
                    if (val % 7 == 0)
                        return (val / 7, "weeks");
                    return (val, "days");
                }
            }
            else if (parts[0] == "0" && parts[1].StartsWith("*/"))
            {
                if (int.TryParse(parts[1].Substring(2), out var val))
                    return (val, "hours");
            }
            else if (parts[0].StartsWith("*/"))
            {
                if (int.TryParse(parts[0].Substring(2), out var val))
                    return (val, "minutes");
            }

            return null;
        }

        /// <summary>
        /// Calculates the next occurrence of a cron expression after the given base time.
        /// </summary>
        public static DateTime? GetNextOccurrence(string cronExpression, DateTime baseTime)
        {
            try
            {
                Console.WriteLine($"========== CRON PARSER ==========");
                Console.WriteLine($"Cron: {cronExpression}");
                Console.WriteLine($"BaseTime (raw): {baseTime:yyyy-MM-dd HH:mm:ss.fff} (Kind: {baseTime.Kind})");
                Console.WriteLine($"BaseTime (UTC): {baseTime.ToUniversalTime():yyyy-MM-dd HH:mm:ss.fff}");
                Console.WriteLine($"BaseTime (Local): {baseTime.ToLocalTime():yyyy-MM-dd HH:mm:ss.fff}");
                Console.WriteLine($"=================================");
                
                // Force UTC
                var utcBase = DateTime.SpecifyKind(baseTime, DateTimeKind.Utc);
                var expression = CronExpression.Parse(cronExpression);
                var next = expression.GetNextOccurrence(utcBase, TimeZoneInfo.Utc);
                
                Console.WriteLine($"Next (raw): {next:yyyy-MM-dd HH:mm:ss.fff}");
                Console.WriteLine($"=================================");
                
                if (next.HasValue)
                {
                    return DateTime.SpecifyKind(next.Value, DateTimeKind.Utc);
                }
                return null;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"❌ Failed to parse cron: {cronExpression} - {ex.Message}");
                return null;
            }
        }
    }
}